"use client";

import {useEffect,useRef,useState,type FormEvent,type PointerEvent} from "react";
import {motion,useReducedMotion} from "framer-motion";
import type {PublicShop} from "../lib/shop";

type Props={data:PublicShop|null};
const mapLink="https://maps.app.goo.gl/XnM3uAKQSqBBd6Wu8?g_st=ic";

function ServiceGlyph({index}:{index:number}){
  const symbols=["✦","◌","⌁","✧","◇","◍"];
  return <span className="service-glyph" aria-hidden="true">{symbols[index%symbols.length]}</span>;
}

function LaundryScene({onMove,onLeave,arabic}:{onMove:(event:PointerEvent<HTMLDivElement>)=>void;onLeave:()=>void;arabic:boolean}){
  return <div className="hero-scene premium-scene" onPointerMove={onMove} onPointerLeave={onLeave} aria-label={arabic?"مشهد عناية بالملابس":"Premium fabric care scene"} role="img">
    <span className="scene-orbit orbit-one"/><span className="scene-orbit orbit-two"/><span className="bubble bubble-one"/><span className="bubble bubble-two"/><span className="bubble bubble-three"/>
    <div className="scene-sun"/><div className="scene-floor"/>
    <span className="fabric-arc arc-one"/><span className="fabric-arc arc-two"/>
    <div className="washing-machine premium-machine"><span className="machine-top"/><span className="machine-light"/><div className="machine-door"><span className="wash-wave"/></div></div>
    <div className="folded-linen"><span/><span/><span/></div><span className="care-label">PEARL<br/>CARE</span>
    <span className="shirt shirt-blue"/><span className="shirt shirt-cream"/><span className="sock sock-one"/><span className="sock sock-two"/>
    <div className="scene-card"><span className="scene-card-dot"/><strong>{arabic?"عناية متقنة بالملابس":"Premium garment care"}</strong><small>{arabic?"نظافة موثوقة لكل قطعة":"Reliable care for every piece"}</small></div>
    <div className="scene-surprise"><span>✦</span>{arabic?"نظيف وجاهز":"Fresh & ready"}</div>
  </div>;
}

export default function Website({data}:Props){
  const [arabic,setArabic]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState(""),[failed,setFailed]=useState(false),[offline,setOffline]=useState(false);
  const scene=useRef<HTMLDivElement>(null);
  const t=(en:string,ar:string)=>arabic?ar:en;
  const reducedMotion=useReducedMotion();
  const reveal=reducedMotion?{}:{initial:{opacity:0,y:22},animate:{opacity:1,y:0},transition:{duration:.58}};
  const name=(arabic?data?.shop?.nameAr:data?.shop?.name)||"PEARL LAUNDRY";
  useEffect(()=>{if(!status)return;const timeout=window.setTimeout(()=>setStatus(""),3000);return()=>window.clearTimeout(timeout);},[status]);
  useEffect(()=>{const update=()=>setOffline(!navigator.onLine);update();window.addEventListener("online",update);window.addEventListener("offline",update);return()=>{window.removeEventListener("online",update);window.removeEventListener("offline",update);};},[]);
  function moveScene(event:PointerEvent<HTMLDivElement>){const node=scene.current;if(!node)return;const rect=node.getBoundingClientRect();node.style.setProperty("--px",String((event.clientX-rect.left)/rect.width-.5));node.style.setProperty("--py",String((event.clientY-rect.top)/rect.height-.5));}
  function resetScene(){scene.current?.style.setProperty("--px","0");scene.current?.style.setProperty("--py","0");}
  async function send(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setStatus("");setFailed(false);const form=event.currentTarget,fields=Object.fromEntries(new FormData(form));try{const response=await fetch("/api/contact",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(fields)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Message could not be sent.");form.reset();setStatus(t("Message sent. Thank you for contacting us.","تم إرسال رسالتك. شكراً لتواصلك معنا."));}catch(error){setFailed(true);setStatus(error instanceof Error?error.message:"Please try again.");}finally{setBusy(false);}}
  return <main dir={arabic?"rtl":"ltr"} lang={arabic?"ar":"en"}>{offline&&<div className="offline-notice" role="alert"><span aria-hidden="true">◌</span><div><strong>{t("You are offline","أنت غير متصل بالإنترنت")}</strong><small>{t("Reconnect to send a message or refresh service details.","أعد الاتصال لإرسال رسالة أو تحديث تفاصيل الخدمات.")}</small></div></div>}{status&&<div className={"site-toast "+(failed?"site-toast-error":"")} role={failed?"alert":"status"}>{status}</div>}
    <header className="site-header"><a className="brand" href="#home"><span className="brand-mark">PL</span><span>{name}<small>{t("LAUNDRY & GARMENT CARE","العناية بالملابس والمفروشات")}</small></span></a><nav aria-label={t("Main navigation","القائمة الرئيسية")}><a href="#services">{t("Services & prices","الخدمات والأسعار")}</a><a href="#about">{t("About us","من نحن")}</a><a href="#contact">{t("Contact","تواصل معنا")}</a></nav><button className="language" onClick={()=>setArabic(value=>!value)}>{arabic?"English":"العربية"}</button></header>
    <section className="hero wrap" id="home"><motion.div className="hero-copy" {...reveal}><p className="eyebrow">{t("A FRESH START, EVERY DAY","بداية منعشة كل يوم")}</p><h1>{t("Care for your clothes.","عناية بملابسك.")}<br/><em>{t("Time for your life.","ووقت لحياتك.")}</em></h1><p className="lead">{t("Reliable cleaning for everyday clothes, home linen and hotel laundry - made simple, fresh and carefully handled.","تنظيف موثوق للملابس اليومية والمفروشات المنزلية وغسيل الفنادق - بعناية وبساطة وانتعاش.")}</p><div className="hero-actions"><a className="button primary" href="#services">{t("Explore our services","استكشف خدماتنا")} <span aria-hidden="true">↗</span></a><a className="button secondary" href="#contact">{t("Talk to our team","تحدث مع فريقنا")}</a></div><div className="hero-trust"><span>✦ {t("Careful handling","عناية دقيقة")}</span><span>◌ {t("Clear pricing","أسعار واضحة")}</span><span>⌁ {t("Hotel ready","جاهزون للفنادق")}</span></div></motion.div><motion.div ref={scene} {...(reducedMotion?{}:{initial:{opacity:0,scale:.94},animate:{opacity:1,scale:1},transition:{delay:.12,duration:.65,ease:[.22,1,.36,1]}})}><LaundryScene onMove={moveScene} onLeave={resetScene} arabic={arabic}/></motion.div></section>
    <section className="services-section" id="services"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">{t("DIGITAL SERVICE MENU","قائمة الخدمات الرقمية")}</p><h2>{t("Laundry care, clearly priced.","عناية بالغسيل بأسعار واضحة.")}</h2></div><p>{t("Choose from the current walk-in catalogue. Prices are in Saudi Riyals and exclude VAT.","اختر من قائمة خدمات العملاء المباشرة. الأسعار بالريال السعودي وغير شاملة الضريبة.")}</p></div>{data?.categories.length?<div className="service-showcase digital-menu">{data.categories.map((category,index)=><motion.article className="service-card" key={category.id} initial={reducedMotion?false:{opacity:0,y:22}} whileInView={reducedMotion?{}:{opacity:1,y:0}} viewport={{once:true,amount:.18}} transition={{delay:index*.08,duration:.45,ease:[.22,1,.36,1]}} whileHover={reducedMotion?{}:{y:-7}} ><div className="service-card-head"><ServiceGlyph index={index}/><span>{String(index+1).padStart(2,"0")}</span></div><h3>{category.name}</h3><p>{t("Select a service, then ask our team to arrange your care.","اختر الخدمة ثم تواصل مع فريقنا لترتيب طلبك.")}</p><ul>{category.services.map((service,itemIndex)=><li key={service.id}><span className="menu-service"><i>{String(itemIndex+1).padStart(2,"0")}</i>{arabic&&service.nameAr?service.nameAr:service.name}</span>{service.price!==null&&service.price>0?<strong><small>SAR</small> {Number(service.price).toFixed(2)}</strong>:<em>{t("Price on request","السعر عند الطلب")}</em>}</li>)}</ul><a href="#contact">{t("Ask our team","اسأل فريقنا")} <span>→</span></a></motion.article>)}</div>:<div className="unavailable"><span className="unavailable-icon" aria-hidden="true">⌁</span><div><strong>{t("Service details are temporarily unavailable.","تفاصيل الخدمات غير متاحة مؤقتاً.")}</strong><p>{t("Please contact the Pearl Laundry team for current services and prices.","يرجى التواصل مع فريق بيرل لمعرفة الخدمات والأسعار الحالية.")}</p><a className="button secondary" href="#contact">{t("Contact the team","تواصل مع الفريق")}</a></div></div>}</div></section>
    <section className="wrap about" id="about"><div><p className="eyebrow">{t("YOUR LOCAL LAUNDRY","مغسلتك المحلية")}</p><h2>{t("Practical care.","عناية عملية.")}<br/>{t("A personal touch.","ولمسة شخصية.")}</h2></div><div><p className="lead">{t("Pearl Laundry supports families, professionals and hotel teams. We help you select the right service, confirm your order and keep every step clear.","تدعم مغسلة بيرل العائلات والمهنيين وفرق الفنادق. نساعدك في اختيار الخدمة المناسبة وتأكيد طلبك وتوضيح كل خطوة.")}</p><div className="about-points"><span>{t("Clothing care","العناية بالملابس")}</span><span>{t("Home linen","المفروشات المنزلية")}</span><span>{t("Hotel laundry","غسيل الفنادق")}</span></div></div></section>
    <section className="contact-section" id="contact"><div className="wrap contact-grid"><div><p className="eyebrow">{t("LET’S TALK","لنتواصل")}</p><h2>{t("How can we help?","كيف يمكننا مساعدتك؟")}</h2><p>{t("Ask about a service, a hotel account or your next visit.","اسأل عن خدمة أو حساب فندق أو زيارتك القادمة.")}</p><dl className="contact-details"><dt>{t("Visit us","موقعنا")}</dt><dd>{data?.shop?.address||t("Contact the team for our location.","تواصل مع الفريق لمعرفة موقعنا.")}</dd><dd><a href={mapLink} target="_blank" rel="noreferrer">{t("Open location in Maps ↗","افتح الموقع على الخريطة ↗")}</a></dd>{data?.shop?.phone&&<><dt>{t("Call us","اتصل بنا")}</dt><dd><a dir="ltr" href={"tel:"+data.shop.phone.replace(/[^+\d]/g,"")}>{data.shop.phone}</a></dd></>}<dt>{t("Email us","راسلنا")}</dt><dd><a href="mailto:pearllaundrysupport@gmail.com">pearllaundrysupport@gmail.com</a></dd></dl></div><form className="contact-form" onSubmit={send}><h3>{t("Send the team a message","أرسل رسالة إلى الفريق")}</h3><label>{t("Your name","اسمك")}<input name="name" required minLength={2} maxLength={100} autoComplete="name"/></label><label>{t("Email address","البريد الإلكتروني")}<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><label>{t("Message","الرسالة")}<textarea name="message" required minLength={10} maxLength={4000} rows={5}/></label><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><p className="privacy-note">{t("We use these details to reply to your enquiry. Do not include payment details, passwords or identity documents.","نستخدم هذه التفاصيل للرد على استفسارك. لا تُدرج معلومات الدفع أو كلمات المرور أو وثائق الهوية.")}</p><button className="button primary" disabled={busy}>{busy?t("Sending…","جارٍ الإرسال…"):t("Send message","إرسال الرسالة")}</button></form></div></section>
    <footer className="wrap site-footer"><span>© {new Date().getFullYear()} {name}</span><span>{t("Laundry care, made simple.","العناية بالغسيل ببساطة.")}</span></footer>
  </main>;
}
