"use client";
import {useState,type FormEvent} from 'react';
import type {PublicShop} from '../lib/shop';

export default function Website({data}:{data:PublicShop|null}){
  const [arabic,setArabic]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[failed,setFailed]=useState(false);
  const t=(en:string,ar:string)=>arabic?ar:en;
  const name=(arabic?data?.shop?.nameAr:data?.shop?.name)||'PEARL LAUNDRY';
  async function send(event:FormEvent<HTMLFormElement>){
    event.preventDefault();setBusy(true);setStatus('');setFailed(false);
    const form=event.currentTarget,fields=Object.fromEntries(new FormData(form));
    try{const response=await fetch('/api/contact',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(fields)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Message could not be sent.');form.reset();setStatus(t('Message sent. Thank you for contacting us.','تم إرسال رسالتك. شكراً لتواصلك معنا.'));}
    catch(error){setFailed(true);setStatus(error instanceof Error?error.message:'Please try again.');}finally{setBusy(false);}
  }
  return <main dir={arabic?'rtl':'ltr'} lang={arabic?'ar':'en'}>
    <header className="site-header"><a className="brand" href="#home"><span className="brand-mark">PL</span><span>{name}<small>{t('LAUNDRY & GARMENT CARE','العناية بالملابس والمفروشات')}</small></span></a><nav aria-label={t('Main navigation','القائمة الرئيسية')}><a href="#services">{t('Services & prices','الخدمات والأسعار')}</a><a href="#about">{t('About us','من نحن')}</a><a href="#contact">{t('Contact','تواصل معنا')}</a></nav><button className="language" onClick={()=>setArabic(value=>!value)}>{arabic?'English':'العربية'}</button></header>
    <section className="hero wrap" id="home"><div><p className="eyebrow">{t('A FRESH START, EVERY DAY','بداية منعشة كل يوم')}</p><h1>{t('Care for your clothes.','عناية بملابسك.')}<br/><em>{t('Time for your life.','ووقت لحياتك.')}</em></h1><p className="lead">{t('Everyday clothing, household linen and hotel laundry. Explore our services and let the Pearl Laundry team help with your next order.','ملابس يومية ومفروشات منزلية وغسيل الفنادق. اكتشف خدماتنا وتواصل مع فريق بيرل لمساعدتك في طلبك القادم.')}</p><div className="hero-actions"><a className="button primary" href="#services">{t('Explore our services','استكشف خدماتنا')} <span aria-hidden="true">↗</span></a><a className="button secondary" href="#contact">{t('Talk to our team','تحدث مع فريقنا')}</a></div><p className="hero-note">{t('For individuals, families and hotel teams.','للأفراد والعائلات وفرق الفنادق.')}</p></div><div className="hero-art" aria-hidden="true"><div className="art-orbit"/><div className="garment-card"><svg viewBox="0 0 240 240" fill="none"><path d="m80 45-47 33 27 43 24-13v93h72v-93l24 13 27-43-47-33c-6 15-20 23-40 23S86 60 80 45Z" fill="white" stroke="#2456cf" strokeWidth="5" strokeLinejoin="round"/><path d="M80 45c4 26 18 40 40 40s36-14 40-40M96 158h48" stroke="#9ebdff" strokeWidth="5" strokeLinecap="round"/></svg><span>{t('A little care goes a long way.','القليل من العناية يصنع الفرق.')}</span></div><div className="art-tag"><span>✦</span>{t('Fresh. Simple. Pearl.','انتعاش. بساطة. بيرل.')}</div></div></section>
    <section className="services-section" id="services"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">{t('MADE FOR YOUR EVERYDAY','لإطلالة يومية متجددة')}</p><h2>{t('Services & prices','الخدمات والأسعار')}</h2></div><p>{t('Current service rates from our shop catalog. Prices are in Saudi Riyals, excluding VAT.','أسعار الخدمات الحالية من قائمة المتجر بالريال السعودي، غير شاملة الضريبة.')}</p></div>{data?.categories.length?<div className="price-grid">{data.categories.map(category=><article className="price-card" key={category.id}><span className="category-number">{String(data.categories.indexOf(category)+1).padStart(2,'0')}</span><h3>{category.name}</h3><ul>{category.services.map(service=><li key={service.id}><span>{arabic&&service.nameAr?service.nameAr:service.name}</span><strong><small>SAR</small> {Number(service.price).toFixed(2)}</strong></li>)}</ul></article>)}</div>:<div className="unavailable">{t('Our price list is temporarily unavailable. Please contact the team for current services and prices.','قائمة الأسعار غير متاحة حالياً. تواصل مع الفريق لمعرفة الخدمات والأسعار.')}</div>}</div></section>
    <section className="wrap about" id="about"><div><p className="eyebrow">{t('YOUR LOCAL LAUNDRY','مغسلتك المحلية')}</p><h2>{t('Practical care.','عناية عملية.')}<br/>{t('A personal touch.','ولمسة شخصية.')}</h2></div><div><p className="lead">{t('Pearl Laundry serves everyday laundry needs and hotel customers. Our team can help you choose the right services, confirm your order and answer questions about your bill.','تقدم بيرل خدمات الغسيل اليومية وخدمات عملاء الفنادق. يساعدك فريقنا في اختيار الخدمات المناسبة وتأكيد طلبك والإجابة عن استفسارات فاتورتك.')}</p><div className="about-points"><span>{t('Clothing care','العناية بالملابس')}</span><span>{t('Home linen','المفروشات المنزلية')}</span><span>{t('Hotel laundry','غسيل الفنادق')}</span></div></div></section>
    <section className="contact-section" id="contact"><div className="wrap contact-grid"><div><p className="eyebrow">{t('LET’S TALK','لنتواصل')}</p><h2>{t('How can we help?','كيف يمكننا مساعدتك؟')}</h2><p>{t('Ask about a service, a hotel account or your next visit.','اسأل عن خدمة أو حساب فندق أو زيارتك القادمة.')}</p><dl className="contact-details"><dt>{t('Visit us','موقعنا')}</dt><dd>{data?.shop?.address||t('Contact the team for our location.','تواصل مع الفريق لمعرفة موقعنا.')}</dd>{data?.shop?.address&&<dd><a href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(data.shop.address+' '+(data.shop.name||'Pearl Laundry'))} target="_blank" rel="noreferrer">{t('Open location in Maps ↗','افتح الموقع على الخريطة ↗')}</a></dd>}{data?.shop?.phone&&<><dt>{t('Call us','اتصل بنا')}</dt><dd><a dir="ltr" href={'tel:'+data.shop.phone.replace(/[^+\d]/g,'')}>{data.shop.phone}</a></dd></>}<dt>{t('Email us','راسلنا')}</dt><dd><a href="mailto:pearllaundrysupport@gmail.com">pearllaundrysupport@gmail.com</a></dd></dl></div><form className="contact-form" onSubmit={send}><h3>{t('Send the team a message','أرسل رسالة إلى الفريق')}</h3><label>{t('Your name','اسمك')}<input name="name" required minLength={2} maxLength={100} autoComplete="name"/></label><label>{t('Email address','البريد الإلكتروني')}<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><label>{t('Message','الرسالة')}<textarea name="message" required minLength={10} maxLength={4000} rows={5}/></label><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><p className="privacy-note">{t('We use these details to reply to your enquiry. Do not include payment details, passwords or identity documents.','نستخدم هذه البيانات للرد على استفسارك. لا تُدرج معلومات الدفع أو كلمات المرور أو وثائق الهوية.')}</p><button className="button primary" disabled={busy}>{busy?t('Sending…','جارٍ الإرسال…'):t('Send message','إرسال الرسالة')}</button>{status&&<p className={failed?'form-status error':'form-status'} role={failed?'alert':'status'}>{status}</p>}</form></div></section>
    <footer className="wrap site-footer"><span>© {new Date().getFullYear()} {name}</span><span>{t('Laundry care, made simple.','العناية بالغسيل ببساطة.')}</span></footer>
  </main>;
}
