server {
    listen 3000;
    listen [::]:3000;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    add_header Cache-Control "no-store" always;

    location / {
        try_files /index.html =404;
    }
}
