import { sql } from "drizzle-orm";
import { check, index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
export const users = sqliteTable("users", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), username: text("username").notNull(), displayName: text("display_name").notNull(),
  portalRole: text("portal_role", { enum: ["super_admin", "admin", "office_staff"] }).notNull(), passwordHash: text("password_hash").notNull(), passwordSalt: text("password_salt").notNull(),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true), mustChangePassword: integer("must_change_password", { mode: "boolean" }).notNull().default(true),
  phone: text("phone").notNull().default(""), passportNumber: text("passport_number").notNull().default(""), passportExpiry: text("passport_expiry"),
  visaStatus: text("visa_status").notNull().default("not_recorded"), visaExpiry: text("visa_expiry"), iqamaNumber: text("iqama_number").notNull().default(""), iqamaExpiry: text("iqama_expiry"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("idx_users_tenant_username").on(table.tenantId, table.username), index("idx_users_tenant_role").on(table.tenantId, table.portalRole), check("users_portal_role_check", sql`${table.portalRole} IN ('super_admin','admin','office_staff')`)]);
export const refreshSessions = sqliteTable("refresh_sessions", {
  id: text("id").primaryKey(), userId: text("user_id").notNull(), tokenHash: text("token_hash").notNull(), expiresAt: text("expires_at").notNull(), revokedAt: text("revoked_at"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("idx_refresh_token_hash").on(table.tokenHash), index("idx_refresh_user").on(table.userId)]);
export const permissionGrants = sqliteTable("permission_grants", {
  id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), userId: text("user_id").notNull(), permission: text("permission").notNull(), resourceScope: text("resource_scope").notNull().default("tenant"), grantedBy: text("granted_by").notNull(), expiresAt: text("expires_at"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("idx_grants_unique").on(table.tenantId, table.userId, table.permission, table.resourceScope)]);
export const permissionRequests = sqliteTable("permission_requests", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), userId: text("user_id").notNull(), task: text("task").notNull(), resourceType: text("resource_type").notNull(), resourceId: text("resource_id").notNull(), reason: text("reason").notNull().default(""), status: text("status", { enum: ["pending", "approved", "denied", "revoked"] }).notNull().default("pending"), reviewedBy: text("reviewed_by"), reviewedAt: text("reviewed_at"), expiresAt: text("expires_at"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, (table) => [index("idx_permission_requests_user_status").on(table.tenantId, table.userId, table.status), index("idx_permission_requests_resource").on(table.tenantId, table.task, table.resourceType, table.resourceId, table.status)]);
export const passwordResetRequests = sqliteTable("password_reset_requests", { id: text("id").primaryKey(), tenantId: text("tenant_id").notNull(), userId: text("user_id").notNull(), status: text("status", { enum: ["pending", "completed", "denied"] }).notNull().default("pending"), requestedAt: text("requested_at").notNull().default(sql`CURRENT_TIMESTAMP`), completedBy: text("completed_by"), completedAt: text("completed_at") }, (table) => [index("idx_password_resets_status").on(table.tenantId, table.status, table.requestedAt)]);
